FROM ruby:2.6-alpine@sha256:dfa9ec3eac436e243b371c0f2e5cc6dba4b65a72b130d1a12e6e216661eb2bc3

RUN apk add --update \
    build-base \
    openssl \
    ca-certificates && \
    rm /var/cache/apk/* && \
    rm -rf /usr/share/ri


WORKDIR /work

COPY Gemfile /work/Gemfile
COPY Gemfile.lock /work/Gemfile.lock
COPY bin/eztv-rss-creator /work/run
RUN chmod +x /work/run

RUN bundle install --without development

CMD "/work/run"
