FROM ruby:2.6-alpine@sha256:2031674465798177bdedb9f99e61830617918d6dbc659694791327a312bfcac7

RUN apk add --update \
    build-base \
    openssl \
    ca-certificates && \
    rm /var/cache/apk/* && \
    rm -rf /usr/share/ri

WORKDIR /work

COPY Gemfile /work/Gemfile
COPY Gemfile.lock /work/Gemfile.lock
COPY bin/eztv-rss-creator /work/run
RUN chmod +x /work/run

RUN bundle install --without development

CMD [ "/work/run" ]
