FROM ruby:2.6-alpine@sha256:deaf1c8117ad605b45f879a84389afcd3030f302af3c9cffd8f827077882ad4d

RUN apk add --update \
    build-base \
    openssl \
    ca-certificates && \
    rm /var/cache/apk/* && \
    rm -rf /usr/share/ri

WORKDIR /work

COPY Gemfile /work/Gemfile
COPY Gemfile.lock /work/Gemfile.lock
COPY bin/eztv-rss-creator /work/run
RUN chmod +x /work/run

RUN bundle install --without development

CMD [ "/work/run" ]
