#!/bin/bash

home="/home/danial"
app="www.tigris.id.au"
mailto="danial"

new_tag=RELEASE-$(date +%Y%m%dT%H%M%S)
old_tag=$(git tag -l RELEASE* | sort -r | head -n1)
old_tag=${old_tag:-"HEAD^"}
daemons=""

update_cron() {
  sudo cp config/cron/* /etc/cron.d
  sudo chown root.root /etc/cron.d/*
}

create_directories() {
  mkdir -p public/cushy
}

restart_daemons() {
  config=$(git diff $old_tag | grep "^--- a/config/nginx")
  if [ "x$config" != "x" ]; then
    sudo cp config/nginx/*.conf /etc/nginx/sites-enabled
    sudo service nginx reload > /dev/null
    daemons="$daemons nginx"
  fi

  config=$(git diff $old_tag | grep "^--- a/config/postfix")
  if [ "x$config" != "x" ]; then
    sudo cp config/postfix/aliases /etc
    sudo cp config/postfix/main.cf /etc/postfix
    sudo newaliases
    sudo service postfix reload > /dev/null
    daemons="$daemons postfix"
  fi

  config=$(git diff $old_tag | grep "^--- a/config/vsftpd")
  if [ "x$config" != "x" ]; then
    sudo cp config/vsftpd/* /etc
    sudo service vsftpd reload
    daemons="$daemons vsftpd"
  fi
}

print_changelog() {
  cat<<EOM

Hi,

$app has been updated with the following changes

The following daemons were reloaded/restarted:

   ${daemons:-"None restarted."}

====================================================

$(git log --stat --no-color $old_tag..HEAD)

EOM
}

cd $home/$app
update_cron
create_directories
restart_daemons

git tag $new_tag
print_changelog | mail -s "Restarted $app" $mailto
